In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r'', sep=';')

In [3]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,3.699,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0                     106823 non-null  int64
 1   DATA INICIAL                   106823 non-null  object
 2   DATA FINAL                     106823 non-null  object
 3   REGIÃO                         106823 non-null  object
 4   ESTADO                         106823 non-null  object
 5   PRODUTO                        106823 non-null  object
 6   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64
 7   UNIDADE DE MEDIDA              106823 non-null  object
 8   PREÇO MÉDIO REVENDA            106823 non-null  float64
 9   DESVIO PADRÃO REVENDA          106823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           106823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 12  MARGEM MÉDIA REVENDA           106823 non-null  object
 13  COEF DE VARIAÇÃO REVENDA       106823 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       106823 non-null  object
 15  DESVIO PADRÃO DISTRIBUIÇÃO     106823 non-null  object
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      106823 non-null  object
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      106823 non-null  object
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  106823 non-null  object
 19  MÊS                            106823 non-null  int64
 20  ANO                            106823 non-null  int64
dtypes: float64(5), int64(4), object(12)
memory usage: 17.1+ MB

In [5]:
l, c = data.shape

In [6]:
pr = data['PREÇO MÉDIO REVENDA'].copy()

In [7]:
data.iloc[[1903]]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
1903,1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2,R$/l,1.694,0.283,...,2.09,-,0.167,-,-,-,-,-,9,2005

In [8]:
data['PREÇO MÉDIO REVENDA (dolar)'] = data['PREÇO MÉDIO REVENDA'] * 6

In [9]:
data['PREÇO MÉDIO REVENDA'] = [f'preço {i}' for i in range(l)]

In [10]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,PREÇO MÉDIO REVENDA (dolar)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,preço 0,0.016,...,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,preço 1,0.114,...,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,preço 2,0.097,...,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,preço 3,0.070,...,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,preço 4,0.078,...,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,7.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,preço 106818,0.065,...,0.818,0.018,2.756,0,2.756,2.756,0,6,2019,21.444
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,preço 106819,0.129,...,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019,20.406
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,preço 106820,0.190,...,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019,17.472
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,preço 106821,0.229,...,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019,18.120
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,preço 106822,0.005,...,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019,22.182

In [11]:
data.iloc[[22, 1, 5678]]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,PREÇO MÉDIO REVENDA (dolar)
22,22,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,952,R$/l,preço 22,0.154,...,0.312,0.140,0.786,0.173,0.326,1.263,0.22,5,2004,6.588
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,preço 1,0.114,...,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,6.972
5678,5678,2008-06-01,2008-06-07,NORTE,ACRE,ETANOL HIDRATADO,36,R$/l,preço 5678,0.203,...,0.408,0.097,1.688,0.226,1.51,2.2606,0.134,6,2008,12.576

In [12]:
data[['PREÇO MÉDIO REVENDA', 'PRODUTO', 'ANO', 'DATA INICIAL']]

       PREÇO MÉDIO REVENDA           PRODUTO   ANO DATA INICIAL
0                  preço 0  ETANOL HIDRATADO  2004   2004-05-09
1                  preço 1  ETANOL HIDRATADO  2004   2004-05-09
2                  preço 2  ETANOL HIDRATADO  2004   2004-05-09
3                  preço 3  ETANOL HIDRATADO  2004   2004-05-09
4                  preço 4  ETANOL HIDRATADO  2004   2004-05-09
...                    ...               ...   ...          ...
106818        preço 106818               GNV  2019   2019-06-23
106819        preço 106819               GNV  2019   2019-06-23
106820        preço 106820               GNV  2019   2019-06-23
106821        preço 106821               GNV  2019   2019-06-23
106822        preço 106822               GNV  2019   2019-06-23

[106823 rows x 4 columns]

In [13]:
data['PREÇO MÉDIO REVENDA'] = pr

In [14]:
del data['Unnamed: 0']

In [15]:
data

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,PREÇO MÉDIO REVENDA (dolar)
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,...,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,7.728
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,...,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,6.972
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,...,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,8.334
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,...,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,7.572
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,...,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,7.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,3.499,...,0.818,0.018,2.756,0,2.756,2.756,0,6,2019,21.444
106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,3.230,...,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019,20.406
106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,2.699,...,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019,17.472
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,...,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019,18.120
106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,3.689,...,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019,22.182

In [16]:
data.to_csv(r'')

In [17]:
data['ANO'].unique()

array([2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019], dtype=int64)

In [18]:
data['ESTADO'] == 'SAO PAULO'

0         False
1         False
2         False
3         False
4         False
          ...
106818    False
106819    False
106820    False
106821     True
106822    False
Name: ESTADO, Length: 106823, dtype: bool

In [19]:
data[data['ESTADO'] == 'SAO PAULO']

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,PREÇO MÉDIO REVENDA (dolar)
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098,5,2004,4.608
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087,5,2004,4.596
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,...,0.209,0.086,0.614,0.063,0.34951,1.412,0.103,5,2004,4.938
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,...,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112,5,2004,5.322
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,...,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104,6,2004,5.364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,3.099,...,0.401,0.045,3.047,0.097,2.8599,3.3481,0.032,6,2019,20.688
106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,3.199,...,0.451,0.047,3.123,0.111,2.885,3.491,0.036,6,2019,21.444
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,0.429,0.044,3.713,0.097,3.52,4.0892,0.026,6,2019,24.852
106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,...,17.679,0.091,49.214,5.071,40.19,72,0.103,6,2019,401.358
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,...,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019,18.120

In [20]:
data.query('ESTADO == "RIO DE JANEIRO"').reset_index()

,index,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,PREÇO MÉDIO REVENDA (dolar)
0,22,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,952,R$/l,1.098,0.154,...,0.312,0.140,0.786,0.173,0.326,1.263,0.22,5,2004,6.588
1,49,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,948,R$/l,1.092,0.157,...,0.284,0.144,0.808,0.175,0.3257,1.2921,0.217,5,2004,6.552
2,76,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,973,R$/l,1.103,0.140,...,0.281,0.127,0.822,0.166,0.38909,1.1859,0.202,5,2004,6.618
3,103,2004-05-30,2004-06-05,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,955,R$/l,1.149,0.156,...,0.3,0.136,0.849,0.188,0.3453,1.3667,0.221,5,2004,6.894
4,130,2004-06-06,2004-06-12,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,966,R$/l,1.165,0.154,...,0.254,0.132,0.911,0.198,0.4,1.3667,0.217,6,2004,6.990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4258,106718,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL,212,R$/l,3.569,0.166,...,0.467,0.047,3.102,0.119,2.886,3.5162,0.038,6,2019,21.414
4259,106745,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL S10,335,R$/l,3.697,0.187,...,0.5,0.051,3.197,0.127,2.9772,3.5388,0.04,6,2019,22.182
4260,106772,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,422,R$/l,4.928,0.165,...,0.538,0.033,4.39,0.097,4.2,4.618,0.022,6,2019,29.568
4261,106799,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GLP,221,R$/13Kg,65.010,5.812,...,17.475,0.089,47.535,3.934,39,58.2,0.083,6,2019,390.060
4262,106817,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GNV,124,R$/m3,3.111,0.260,...,0.707,0.084,2.404,0.174,2.126,2.7909,0.072,6,2019,18.666

In [21]:
data[((data['ESTADO'] == 'SAO PAULO') | (data['ESTADO'] == 'RIO DE JANEIRO')) & (data['PRODUTO'] == 'GASOLINA COMUM')]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,PREÇO MÉDIO REVENDA (dolar)
12086,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1071,R$/l,2.045,0.109,1.700,...,0.254,0.053,1.791,0.047,1.6363,1.9594,0.026,5,2004,12.270
12087,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,GASOLINA COMUM,4107,R$/l,1.891,0.101,1.570,...,0.235,0.053,1.656,0.064,1.38,1.944,0.039,5,2004,11.346
12113,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.040,0.113,1.700,...,0.252,0.055,1.788,0.049,1.5943,1.99651,0.027,5,2004,12.240
12114,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,GASOLINA COMUM,4133,R$/l,1.888,0.101,1.540,...,0.233,0.053,1.655,0.063,1.38,1.9319,0.038,5,2004,11.328
12140,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.042,0.108,1.700,...,0.252,0.053,1.79,0.046,1.63596,2.2137,0.026,5,2004,12.252
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106479,2019-06-09,2019-06-15,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.210,0.177,3.759,...,0.425,0.042,3.785,0.096,3.52,4.1007,0.025,6,2019,25.260
106623,2019-06-16,2019-06-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,418,R$/l,4.927,0.160,4.599,...,0.544,0.032,4.383,0.1,4.1972,4.6239,0.023,6,2019,29.562
106629,2019-06-16,2019-06-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1635,R$/l,4.168,0.177,3.679,...,0.443,0.042,3.725,0.096,3.502,4.0892,0.026,6,2019,25.008
106772,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,422,R$/l,4.928,0.165,4.599,...,0.538,0.033,4.39,0.097,4.2,4.618,0.022,6,2019,29.568
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,0.429,0.044,3.713,0.097,3.52,4.0892,0.026,6,2019,24.852

In [22]:
data.query('ESTADO == "SAO PAULO" and ANO == 2015 and PRODUTO == "GASOLINA COMUM"')

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,PREÇO MÉDIO REVENDA (dolar)
71717,2015-01-04,2015-01-10,SUDESTE,SAO PAULO,GASOLINA COMUM,2368,R$/l,2.905,0.110,2.569,...,0.408,0.038,2.497,0.08,2.21,2.8843,0.032,1,2015,17.430
71869,2015-01-11,2015-01-17,SUDESTE,SAO PAULO,GASOLINA COMUM,2367,R$/l,2.908,0.113,2.499,...,0.403,0.039,2.505,0.078,2.24,2.8843,0.031,1,2015,17.448
72022,2015-01-18,2015-01-24,SUDESTE,SAO PAULO,GASOLINA COMUM,2368,R$/l,2.930,0.114,2.599,...,0.418,0.039,2.512,0.075,2.24,2.7381,0.03,1,2015,17.580
72174,2015-01-25,2015-01-31,SUDESTE,SAO PAULO,GASOLINA COMUM,2369,R$/l,2.930,0.109,2.559,...,0.416,0.037,2.514,0.071,2.27,2.8458,0.028,1,2015,17.580
72327,2015-02-01,2015-02-07,SUDESTE,SAO PAULO,GASOLINA COMUM,2366,R$/l,3.100,0.157,2.660,...,0.542,0.051,2.558,0.111,2.2367,2.9433,0.043,2,2015,18.600
72480,2015-02-08,2015-02-14,SUDESTE,SAO PAULO,GASOLINA COMUM,2360,R$/l,3.157,0.124,2.699,...,0.475,0.039,2.682,0.114,2.275,2.9861,0.043,2,2015,18.942
72632,2015-02-15,2015-02-21,SUDESTE,SAO PAULO,GASOLINA COMUM,2361,R$/l,3.172,0.123,2.799,...,0.451,0.039,2.721,0.102,2.285,2.9861,0.037,2,2015,19.032
72785,2015-02-22,2015-02-28,SUDESTE,SAO PAULO,GASOLINA COMUM,2360,R$/l,3.170,0.119,2.749,...,0.422,0.038,2.748,0.089,2.32,2.993,0.032,2,2015,19.020
72938,2015-03-01,2015-03-07,SUDESTE,SAO PAULO,GASOLINA COMUM,2360,R$/l,3.177,0.119,2.799,...,0.418,0.037,2.759,0.087,2.36,2.993,0.032,3,2015,19.062
73089,2015-03-08,2015-03-14,SUDESTE,SAO PAULO,GASOLINA COMUM,2361,R$/l,3.185,0.126,2.749,...,0.415,0.040,2.77,0.079,2.5,3.0442,0.029,3,2015,19.110
73242,2015-03-15,2015-03-21,SUDESTE,SAO PAULO,GASOLINA COMUM,2362,R$/l,3.173,0.121,2.829,...,0.412,0.038,2.761,0.081,2.51,3.0442,0.029,3,2015,19.038
73394,2015-03-22,2015-03-28,SUDESTE,SAO PAULO,GASOLINA COMUM,2367,R$/l,3.168,0.125,2.749,...,0.414,0.039,2.754,0.08,2.52,2.9564,0.029,3,2015,19.008
73547,2015-03-29,2015-04-04,SUDESTE,SAO PAULO,GASOLINA COMUM,2369,R$/l,3.170,0.133,2.799,...,0.426,0.042,2.744,0.082,2.424,2.94,0.03,3,2015,19.020
73700,2015-04-05,2015-04-11,SUDESTE,SAO PAULO,GASOLINA COMUM,2360,R$/l,3.149,0.128,2.749,...,0.409,0.041,2.74,0.083,2.361,2.9921,0.03,4,2015,18.894
73853,2015-04-12,2015-04-18,SUDESTE,SAO PAULO,GASOLINA COMUM,2359,R$/l,3.154,0.128,2.799,...,0.409,0.041,2.745,0.082,2.361,2.9921,0.03,4,2015,18.924
74005,2015-04-19,2015-04-25,SUDESTE,SAO PAULO,GASOLINA COMUM,2359,R$/l,3.148,0.129,2.799,...,0.409,0.041,2.739,0.08,2.5,2.963,0.029,4,2015,18.888
74158,2015-04-26,2015-05-02,SUDESTE,SAO PAULO,GASOLINA COMUM,2362,R$/l,3.141,0.135,2.799,...,0.404,0.043,2.737,0.082,2.441,2.963,0.03,4,2015,18.846
74310,2015-05-03,2015-05-09,SUDESTE,SAO PAULO,GASOLINA COMUM,2359,R$/l,3.134,0.133,2.749,...,0.394,0.042,2.74,0.079,2.502,2.963,0.029,5,2015,18.804
74462,2015-05-10,2015-05-16,SUDESTE,SAO PAULO,GASOLINA COMUM,2354,R$/l,3.128,0.132,2.749,...,0.387,0.042,2.741,0.075,2.51,2.963,0.027,5,2015,18.768
74615,2015-05-17,2015-05-23,SUDESTE,SAO PAULO,GASOLINA COMUM,2355,R$/l,3.138,0.138,2.749,...,0.404,0.044,2.734,0.077,2.5,2.963,0.028,5,2015,18.828
74768,2015-05-24,2015-05-30,SUDESTE,SAO PAULO,GASOLINA COMUM,2356,R$/l,3.141,0.138,2.799,...,0.416,0.044,2.725,0.08,2.441,2.96,0.029,5,2015,18.846
74921,2015-05-31,2015-06-06,SUDESTE,SAO PAULO,GASOLINA COMUM,2351,R$/l,3.126,0.135,2.749,...,0.407,0.043,2.719,0.08,2.5,2.9622,0.029,5,2015,18.756
75074,2015-06-07,2015-06-13,SUDESTE,SAO PAULO,GASOLINA COMUM,2353,R$/l,3.130,0.131,2.749,...,0.405,0.042,2.725,0.078,2.4882,2.9622,0.029,6,2015,18.780
75226,2015-06-14,2015-06-20,SUDESTE,SAO PAULO,GASOLINA COMUM,2356,R$/l,3.143,0.133,2.749,...,0.416,0.042,2.727,0.076,2.45,2.9555,0.028,6,2015,18.858
75378,2015-06-21,2015-06-27,SUDESTE,SAO PAULO,GASOLINA COMUM,2356,R$/l,3.126,0.133,2.779,...,0.407,0.043,2.719,0.079,2.45,2.9555,0.029,6,2015,18.756
75531,2015-06-28,2015-07-04,SUDESTE,SAO PAULO,GASOLINA COMUM,2353,R$/l,3.110,0.133,2.719,...,0.391,0.043,2.719,0.078,2.5,2.9324,0.029,6,2015,18.660
75683,2015-07-05,2015-07-11,SUDESTE,SAO PAULO,GASOLINA COMUM,2349,R$/l,3.123,0.136,2.719,...,0.402,0.044,2.721,0.078,2.434,2.9324,0.029,7,2015,18.738
75835,2015-07-12,2015-07-18,SUDESTE,SAO PAULO,GASOLINA COMUM,2347,R$/l,3.110,0.134,2.719,...,0.394,0.043,2.716,0.075,2.473,2.965,0.028,7,2015,18.660
75988,2015-07-19,2015-07-25,SUDESTE,SAO PAULO,GASOLINA COMUM,2352,R$/l,3.099,0.134,2.719,...,0.385,0.043,2.714,0.076,2.4747,2.965,0.028,7,2015,18.594
76142,2015-07-26,2015-08-01,SUDESTE,SAO PAULO,GASOLINA COMUM,2347,R$/l,3.106,0.144,2.749,...,0.394,0.046,2.712,0.074,2.39,2.921,0.027,7,2015,18.636
76295,2015-08-02,2015-08-08,SUDESTE,SAO PAULO,GASOLINA COMUM,2346,R$/l,3.088,0.137,2.749,...,0.379,0.044,2.709,0.073,2.374,2.921,0.027,8,2015,18.528
76448,2015-08-09,2015-08-15,SUDESTE,SAO PAULO,GASOLINA COMUM,2352,R$/l,3.100,0.138,2.749,...,0.391,0.045,2.709,0.074,2.4299,2.92,0.027,8,2015,18.600
76601,2015-08-23,2015-08-29,SUDESTE,SAO PAULO,GASOLINA COMUM,767,R$/l,3.076,0.141,2.749,...,0.375,0.046,2.701,0.08,2.4709,2.8819,0.03,8,2015,18.456
76752,2015-08-30,2015-09-05,SUDESTE,SAO PAULO,GASOLINA COMUM,767,R$/l,3.089,0.134,2.779,...,0.39,0.043,2.699,0.077,2.4709,2.8741,0.029,8,2015,18.534
76904,2015-09-06,2015-09-12,SUDESTE,SAO PAULO,GASOLINA COMUM,767,R$/l,3.087,0.138,2.779,...,0.377,0.045,2.71,0.073,2.5,2.9267,0.027,9,2015,18.522
77055,2015-09-13,2015-09-19,SUDESTE,SAO PAULO,GASOLINA COMUM,767,R$/l,3.074,0.143,2.749,...,0.383,0.047,2.691,0.076,2.495,2.8811,0.028,9,2015,18.444
77208,2015-09-20,2015-09-26,SUDESTE,SAO PAULO,GASOLINA COMUM,857,R$/l,3.103,0.144,2.789,...,0.389,0.046,2.714,0.085,2.495,2.9234,0.031,9,2015,18.618
77361,2015-09-27,2015-10-03,SUDESTE,SAO PAULO,GASOLINA COMUM,853,R$/l,3.133,0.133,2.799,...,0.405,0.042,2.728,0.086,2.495,2.9309,0.032,9,2015,18.798
77513,2015-10-04,2015-10-10,SUDESTE,SAO PAULO,GASOLINA COMUM,859,R$/l,3.278,0.154,2.919,...,0.449,0.047,2.829,0.116,2.459,3.1382,0.041,10,2015,19.668
77666,2015-10-11,2015-10-17,SUDESTE,SAO PAULO,GASOLINA COMUM,858,R$/l,3.320,0.154,2.899,...,0.451,0.046,2.869,0.113,2.459,3.1382,0.039,10,2015,19.920
77817,2015-10-18,2015-10-24,SUDESTE,SAO PAULO,GASOLINA COMUM,998,R$/l,3.320,0.160,2.899,...,0.421,0.048,2.899,0.109,2.5,3.179,0.038,10,2015,19.920
77969,2015-10-25,2015-10-31,SUDESTE,SAO PAULO,GASOLINA COMUM,1002,R$/l,3.335,0.143,2.939,...,0.428,0.043,2.907,0.104,2.5,3.16,0.036,10,2015,20.010
78121,2015-11-01,2015-11-07,SUDESTE,SAO PAULO,GASOLINA COMUM,996,R$/l,3.397,0.145,2.959,...,0.457,0.043,2.94,0.104,2.59,3.209,0.035,11,2015,20.382
78273,2015-11-08,2015-11-14,SUDESTE,SAO PAULO,GASOLINA COMUM,1000,R$/l,3.458,0.151,3.059,...,0.47,0.044,2.988,0.099,2.59,3.209,0.033,11,2015,20.748
78426,2015-11-15,2015-11-21,SUDESTE,SAO PAULO,GASOLINA COMUM,1173,R$/l,3.445,0.148,3.059,...,0.446,0.043,2.999,0.09,2.59,3.1925,0.03,11,2015,20.670
78578,2015-11-22,2015-11-28,SUDESTE,SAO PAULO,GASOLINA COMUM,1176,R$/l,3.477,0.142,3.149,...,0.462,0.041,3.015,0.09,2.59,3.2228,0.03,11,2015,20.862
78731,2015-11-29,2015-12-05,SUDESTE,SAO PAULO,GASOLINA COMUM,1173,R$/l,3.507,0.142,3.169,...,0.475,0.040,3.032,0.087,2.59,3.2366,0.029,11,2015,21.042
78881,2015-12-06,2015-12-12,SUDESTE,SAO PAULO,GASOLINA COMUM,1416,R$/l,3.495,0.139,3.149,...,0.45,0.040,3.045,0.086,2.6626,3.34,0.028,12,2015,20.970
79032,2015-12-13,2015-12-19,SUDESTE,SAO PAULO,GASOLINA COMUM,1415,R$/l,3.501,0.145,3.079,...,0.453,0.041,3.048,0.085,2.835,3.316,0.028,12,2015,21.006
79184,2015-12-20,2015-12-26,SUDESTE,SAO PAULO,GASOLINA COMUM,1629,R$/l,3.515,0.135,3.159,...,0.454,0.038,3.061,0.081,2.846,3.41,0.026,12,2015,21.090
79335,2015-12-27,2016-01-02,SUDESTE,SAO PAULO,GASOLINA COMUM,1625,R$/l,3.508,0.134,3.149,...,0.45,0.038,3.058,0.08,2.84,3.3353,0.026,12,2015,21.048

In [23]:
s1 = data['ESTADO'] == 'SAO PAULO'
s2 = data['ESTADO'] == 'RIO DE JANEIRO'
s3 = data['PRODUTO'] == 'GASOLINA COMUM'
s4 = data['ANO'] == 2005

s5 = (s1 | s2) & s3 & s4
data[s5]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,PREÇO MÉDIO REVENDA (dolar)
13004,2005-01-02,2005-01-08,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1096,R$/l,2.297,0.098,1.990,...,0.213,0.043,2.084,0.041,1.95583,2.3374,0.02,1,2005,13.782
13005,2005-01-02,2005-01-08,SUDESTE,SAO PAULO,GASOLINA COMUM,4084,R$/l,2.202,0.090,1.870,...,0.255,0.041,1.947,0.052,1.63,2.289,0.027,1,2005,13.212
13031,2005-01-09,2005-01-15,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1069,R$/l,2.292,0.101,2.039,...,0.213,0.044,2.079,0.041,1.963,2.3312,0.02,1,2005,13.752
13032,2005-01-09,2005-01-15,SUDESTE,SAO PAULO,GASOLINA COMUM,4135,R$/l,2.195,0.092,1.890,...,0.25,0.042,1.945,0.054,1.477,2.389,0.028,1,2005,13.170
13058,2005-01-16,2005-01-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1094,R$/l,2.296,0.099,2.000,...,0.213,0.043,2.083,0.039,1.9742,2.3379,0.019,1,2005,13.776
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14273,2005-12-11,2005-12-17,SUDESTE,SAO PAULO,GASOLINA COMUM,3551,R$/l,2.365,0.094,2.089,...,0.253,0.040,2.112,0.051,1.95,2.4842,0.024,12,2005,14.190
14299,2005-12-18,2005-12-24,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,909,R$/l,2.515,0.115,2.219,...,0.235,0.046,2.28,0.056,2.1166,2.5275,0.025,12,2005,15.090
14300,2005-12-18,2005-12-24,SUDESTE,SAO PAULO,GASOLINA COMUM,3535,R$/l,2.368,0.094,2.040,...,0.251,0.040,2.117,0.05,2.0008,2.461,0.024,12,2005,14.208
14326,2005-12-25,2005-12-31,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,933,R$/l,2.508,0.116,2.219,...,0.229,0.046,2.279,0.055,2.1094,2.5194,0.024,12,2005,15.048
14327,2005-12-25,2005-12-31,SUDESTE,SAO PAULO,GASOLINA COMUM,3380,R$/l,2.372,0.096,2.089,...,0.253,0.040,2.119,0.05,2.0006,2.455,0.024,12,2005,14.232

In [24]:
lista = [2, 2005, 2009]
data.query('ANO in @lista')

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,PREÇO MÉDIO REVENDA (dolar)
918,2005-01-02,2005-01-08,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,128,R$/l,1.686,0.110,1.490,...,0.35,0.065,1.336,0.12,0.975,1.6,0.09,1,2005,10.116
919,2005-01-02,2005-01-08,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,381,R$/l,1.599,0.089,1.390,...,0.396,0.056,1.203,0.103,1.021,1.4562,0.086,1,2005,9.594
920,2005-01-02,2005-01-08,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,201,R$/l,1.816,0.092,1.630,...,0.41,0.051,1.406,0.12,1.0752,1.696,0.085,1,2005,10.896
921,2005-01-02,2005-01-08,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,160,R$/l,1.714,0.054,1.590,...,0.362,0.032,1.352,0.137,0.9702,1.6313,0.101,1,2005,10.284
922,2005-01-02,2005-01-08,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,1.641,0.071,1.500,...,0.221,0.043,1.42,0.13,1.1369,1.5933,0.092,1,2005,9.846
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51398,2009-12-27,2010-01-02,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL,398,R$/l,1.984,0.076,1.789,...,0.246,0.038,1.738,0.037,1.643,1.8633,0.021,12,2009,11.904
51399,2009-12-27,2010-01-02,SUDESTE,SAO PAULO,ÓLEO DIESEL,1711,R$/l,1.963,0.068,1.730,...,0.26,0.035,1.703,0.044,1.5499,1.949,0.026,12,2009,11.778
51400,2009-12-27,2010-01-02,SUL,PARANA,ÓLEO DIESEL,411,R$/l,1.926,0.064,1.750,...,0.182,0.033,1.744,0.033,1.66,1.88,0.019,12,2009,11.556
51401,2009-12-27,2010-01-02,SUL,RIO GRANDE DO SUL,ÓLEO DIESEL,438,R$/l,2.041,0.063,1.690,...,0.275,0.031,1.766,0.038,1.663,1.8864,0.022,12,2009,12.246
51402,2009-12-27,2010-01-02,SUL,SANTA CATARINA,ÓLEO DIESEL,294,R$/l,2.017,0.059,1.850,...,0.25,0.029,1.767,0.035,1.6423,1.8339,0.02,12,2009,12.102

In [25]:
for l, dado in data.head(10).iterrows():
    print(f'{l} -> {dado["ANO"]}')

0 -> 2004
1 -> 2004
2 -> 2004
3 -> 2004
4 -> 2004
5 -> 2004
6 -> 2004
7 -> 2004
8 -> 2004
9 -> 2004

In [26]:
data['DATA INICIAL'] = pd.to_datetime(data['DATA INICIAL'])
data['DATA FINAL'] = pd.to_datetime(data['DATA FINAL'])

In [27]:
data['MARGEM MÉDIA REVENDA'] = pd.to_numeric(data['MARGEM MÉDIA REVENDA'], errors='coerce')

In [28]:
data.columns

Index(['DATA INICIAL', 'DATA FINAL', 'REGIÃO', 'ESTADO', 'PRODUTO',
       'NÚMERO DE POSTOS PESQUISADOS', 'UNIDADE DE MEDIDA',
       'PREÇO MÉDIO REVENDA', 'DESVIO PADRÃO REVENDA', 'PREÇO MÍNIMO REVENDA',
       'PREÇO MÁXIMO REVENDA', 'MARGEM MÉDIA REVENDA',
       'COEF DE VARIAÇÃO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO',
       'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO',
       'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO', 'MÊS',
       'ANO', 'PREÇO MÉDIO REVENDA (dolar)'],
      dtype='object')

In [29]:
for tipo in ['PREÇO MÉDIO DISTRIBUIÇÃO', 'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO', 'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO']:
    data[tipo] = pd.to_numeric(data[tipo], errors='coerce')

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   106823 non-null  datetime64[ns]
 1   DATA FINAL                     106823 non-null  datetime64[ns]
 2   REGIÃO                         106823 non-null  object
 3   ESTADO                         106823 non-null  object
 4   PRODUTO                        106823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64
 6   UNIDADE DE MEDIDA              106823 non-null  object
 7   PREÇO MÉDIO REVENDA            106823 non-null  float64
 8   DESVIO PADRÃO REVENDA          106823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           106823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 11  MARGEM MÉDIA REVENDA           103392 non-null  float64
 12  COEF DE VARIAÇÃO REVENDA       106823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       103423 non-null  float64
 14  DESVIO PADRÃO DISTRIBUIÇÃO     103423 non-null  float64
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      103423 non-null  float64
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      103423 non-null  float64
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  103423 non-null  float64
 18  MÊS                            106823 non-null  int64
 19  ANO                            106823 non-null  int64
 20  PREÇO MÉDIO REVENDA (dolar)    106823 non-null  float64
dtypes: datetime64[ns](2), float64(12), int64(3), object(4)
memory usage: 17.1+ MB

In [31]:
data_fill = data.copy()

In [32]:
data_fill.fillna(0, inplace=True)

In [33]:
data_fill.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   106823 non-null  datetime64[ns]
 1   DATA FINAL                     106823 non-null  datetime64[ns]
 2   REGIÃO                         106823 non-null  object
 3   ESTADO                         106823 non-null  object
 4   PRODUTO                        106823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64
 6   UNIDADE DE MEDIDA              106823 non-null  object
 7   PREÇO MÉDIO REVENDA            106823 non-null  float64
 8   DESVIO PADRÃO REVENDA          106823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           106823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 11  MARGEM MÉDIA REVENDA           106823 non-null  float64
 12  COEF DE VARIAÇÃO REVENDA       106823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       106823 non-null  float64
 14  DESVIO PADRÃO DISTRIBUIÇÃO     106823 non-null  float64
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      106823 non-null  float64
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      106823 non-null  float64
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  106823 non-null  float64
 18  MÊS                            106823 non-null  int64
 19  ANO                            106823 non-null  int64
 20  PREÇO MÉDIO REVENDA (dolar)    106823 non-null  float64
dtypes: datetime64[ns](2), float64(12), int64(3), object(4)
memory usage: 17.1+ MB

In [34]:
data_drop= data.copy()

In [35]:
data_drop.dropna(inplace=True)

In [36]:
data_drop.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 103392 entries, 0 to 106822
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   103392 non-null  datetime64[ns]
 1   DATA FINAL                     103392 non-null  datetime64[ns]
 2   REGIÃO                         103392 non-null  object
 3   ESTADO                         103392 non-null  object
 4   PRODUTO                        103392 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   103392 non-null  int64
 6   UNIDADE DE MEDIDA              103392 non-null  object
 7   PREÇO MÉDIO REVENDA            103392 non-null  float64
 8   DESVIO PADRÃO REVENDA          103392 non-null  float64
 9   PREÇO MÍNIMO REVENDA           103392 non-null  float64
 10  PREÇO MÁXIMO REVENDA           103392 non-null  float64
 11  MARGEM MÉDIA REVENDA           103392 non-null  float64
 12  COEF DE VARIAÇÃO REVENDA       103392 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       103392 non-null  float64
 14  DESVIO PADRÃO DISTRIBUIÇÃO     103392 non-null  float64
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      103392 non-null  float64
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      103392 non-null  float64
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  103392 non-null  float64
 18  MÊS                            103392 non-null  int64
 19  ANO                            103392 non-null  int64
 20  PREÇO MÉDIO REVENDA (dolar)    103392 non-null  float64
dtypes: datetime64[ns](2), float64(12), int64(3), object(4)
memory usage: 17.4+ MB

In [37]:
data_drop.describe()

,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,PREÇO MÉDIO REVENDA (dolar)
count,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000
mean,240.511935,10.784472,0.652589,9.334931,12.458686,2.225151,0.045749,8.559322,0.559441,7.414814,9.805621,0.046640,6.485067,2011.737001,64.706834
std,408.039174,17.685852,1.346422,15.024383,20.801190,4.375085,0.024488,13.603686,1.256914,11.681366,15.933999,0.042114,3.442155,4.410491,106.115110
min,1.000000,0.766000,0.000000,0.590000,0.999000,0.001000,0.000000,0.506000,0.000000,0.325700,0.599200,0.000000,1.000000,2004.000000,4.596000
25%,47.000000,2.073000,0.073000,1.900000,2.330000,0.282000,0.030000,1.795000,0.047000,1.674400,1.945600,0.021000,4.000000,2008.000000,12.438000
50%,108.000000,2.723000,0.115000,2.509000,3.000000,0.383000,0.042000,2.335000,0.077000,2.220000,2.507050,0.031000,6.000000,2012.000000,16.338000
75%,251.000000,3.745000,0.190000,3.490000,4.150000,0.560000,0.058000,3.307000,0.151000,3.142800,3.520000,0.061000,9.000000,2016.000000,22.470000
max,4167.000000,99.357000,10.748000,90.000000,120.000000,36.847000,0.262000,83.137000,18.385000,83.000000,94.500000,0.780000,12.000000,2019.000000,596.142000

In [38]:
data_drop.describe().loc['max']

NÚMERO DE POSTOS PESQUISADOS     4167.000
PREÇO MÉDIO REVENDA                99.357
DESVIO PADRÃO REVENDA              10.748
PREÇO MÍNIMO REVENDA               90.000
PREÇO MÁXIMO REVENDA              120.000
MARGEM MÉDIA REVENDA               36.847
COEF DE VARIAÇÃO REVENDA            0.262
PREÇO MÉDIO DISTRIBUIÇÃO           83.137
DESVIO PADRÃO DISTRIBUIÇÃO         18.385
PREÇO MÍNIMO DISTRIBUIÇÃO          83.000
PREÇO MÁXIMO DISTRIBUIÇÃO          94.500
COEF DE VARIAÇÃO DISTRIBUIÇÃO       0.780
MÊS                                12.000
ANO                              2019.000
PREÇO MÉDIO REVENDA (dolar)       596.142
Name: max, dtype: float64

In [39]:
data_drop.mean()

C:\Users\Fabio\AppData\Local\Temp\ipykernel_3272\2627008333.py:1: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  data_drop.mean()
C:\Users\Fabio\AppData\Local\Temp\ipykernel_3272\2627008333.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data_drop.mean()

NÚMERO DE POSTOS PESQUISADOS      240.511935
PREÇO MÉDIO REVENDA                10.784472
DESVIO PADRÃO REVENDA               0.652589
PREÇO MÍNIMO REVENDA                9.334931
PREÇO MÁXIMO REVENDA               12.458686
MARGEM MÉDIA REVENDA                2.225151
COEF DE VARIAÇÃO REVENDA            0.045749
PREÇO MÉDIO DISTRIBUIÇÃO            8.559322
DESVIO PADRÃO DISTRIBUIÇÃO          0.559441
PREÇO MÍNIMO DISTRIBUIÇÃO           7.414814
PREÇO MÁXIMO DISTRIBUIÇÃO           9.805621
COEF DE VARIAÇÃO DISTRIBUIÇÃO       0.046640
MÊS                                 6.485067
ANO                              2011.737001
PREÇO MÉDIO REVENDA (dolar)        64.706834
dtype: float64

In [40]:
sorted(data_drop['PRODUTO'].unique())

['ETANOL HIDRATADO',
 'GASOLINA COMUM',
 'GLP',
 'GNV',
 'ÓLEO DIESEL',
 'ÓLEO DIESEL S10']

In [41]:
data_drop['ESTADO'].value_counts()

BAHIA                  4263
RIO DE JANEIRO         4262
SAO PAULO              4261
RIO GRANDE DO SUL      4249
PARAIBA                4240
PERNAMBUCO             4236
SERGIPE                4202
SANTA CATARINA         4164
MINAS GERAIS           4142
ESPIRITO SANTO         4079
MATO GROSSO DO SUL     4076
ALAGOAS                4020
RIO GRANDE DO NORTE    3999
CEARA                  3964
PARANA                 3902
AMAZONAS               3713
MATO GROSSO            3703
PARA                   3477
MARANHAO               3470
ACRE                   3463
RORAIMA                3457
TOCANTINS              3453
GOIAS                  3449
RONDONIA               3441
PIAUI                  3394
DISTRITO FEDERAL       3317
AMAPA                  2996
Name: ESTADO, dtype: int64

In [42]:
data_drop['ANO'].to_frame()

         ANO
0       2004
1       2004
2       2004
3       2004
4       2004
...      ...
106818  2019
106819  2019
106820  2019
106821  2019
106822  2019

[103392 rows x 1 columns]

In [43]:
num = pd.DataFrame({
    'a' : [1, 2, 3, 4],
    'b' : [10, 20, 30, 40],
    'c' : [100, 200, 300, 400]
})

In [44]:
num

   a   b    c
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400

In [45]:
num['soma_tot'] = num.apply(lambda x: x.sum(), axis=1)

In [46]:
num

   a   b    c  soma_tot
0  1  10  100       111
1  2  20  200       222
2  3  30  300       333
3  4  40  400       444

In [47]:
num.loc['soma_col'] = num.apply(lambda x : x.sum(), axis=0)

In [48]:
num

           a    b     c  soma_tot
0          1   10   100       111
1          2   20   200       222
2          3   30   300       333
3          4   40   400       444
soma_col  10  100  1000      1110

In [49]:
data_drop.groupby('ESTADO').describe()

                    NÚMERO DE POSTOS PESQUISADOS                            \
                                           count         mean          std
ESTADO
ACRE                                      3463.0    44.268842    19.810211
ALAGOAS                                   4020.0    59.554478    38.021769
AMAPA                                     2996.0    23.294393    12.605830
AMAZONAS                                  3713.0    93.718556    57.529211
BAHIA                                     4263.0   281.310579   150.449791
CEARA                                     3964.0   170.384460    94.479674
DISTRITO FEDERAL                          3317.0    77.780223    40.934864
ESPIRITO SANTO                            4079.0   135.411620    81.656726
GOIAS                                     3449.0   277.500145   119.588668
MARANHAO                                  3470.0   108.195101    39.275585
MATO GROSSO                               3703.0   122.479611    48.015952
MATO GROSSO DO SUL                        4076.0   107.681796    62.648820
MINAS GERAIS                              4142.0   697.658619   412.195533
PARA                                      3477.0   139.579810    59.645754
PARAIBA                                   4240.0    81.934198    46.791832
PARANA                                    3902.0   446.426704   231.575009
PERNAMBUCO                                4236.0   214.823182   130.561029
PIAUI                                     3394.0    73.049499    25.722153
RIO DE JANEIRO                            4262.0   451.209995   267.436114
RIO GRANDE DO NORTE                       3999.0    77.035509    41.906525
RIO GRANDE DO SUL                         4249.0   401.537068   251.274375
RONDONIA                                  3441.0    81.767219    26.587507
RORAIMA                                   3457.0    24.539196    14.321286
SANTA CATARINA                            4164.0   255.159222   163.235048
SAO PAULO                                 4261.0  1594.034264  1015.331098
SERGIPE                                   4202.0    38.239172    19.310112
TOCANTINS                                 3453.0    59.507964    24.363098

                                                         PREÇO MÉDIO REVENDA  \
                      min    25%     50%     75%     max               count
ESTADO
ACRE                  1.0   31.0    42.0    52.0   119.0              3463.0
ALAGOAS               1.0   29.0    54.0    95.0   178.0              4020.0
AMAPA                 1.0   13.0    21.0    31.0    55.0              2996.0
AMAZONAS              1.0   48.0    83.0   122.0   383.0              3713.0
BAHIA                 4.0  199.0   316.0   409.0   625.0              4263.0
CEARA                 3.0  114.0   200.0   228.0   493.0              3964.0
DISTRITO FEDERAL      1.0   42.0    80.0   103.0   419.0              3317.0
ESPIRITO SANTO        1.0   73.0   146.0   189.0   334.0              4079.0
GOIAS                 1.0  217.0   254.0   341.0   766.0              3449.0
MARANHAO              1.0   82.0   110.0   141.0   204.0              3470.0
MATO GROSSO           1.0   96.0   134.0   142.0   269.0              3703.0
MATO GROSSO DO SUL    1.0   68.0   115.0   141.0   298.0              4076.0
MINAS GERAIS          1.0  384.0   838.0   993.0  1532.0              4142.0
PARA                  1.0   96.0   131.0   194.0   272.0              3477.0
PARAIBA               1.0   40.0    96.5   120.0   200.0              4240.0
PARANA                1.0  279.0   496.0   570.0   997.0              3902.0
PERNAMBUCO            2.0   96.0   235.0   321.0   539.0              4236.0
PIAUI                 1.0   54.0    69.0    98.0   145.0              3394.0
RIO DE JANEIRO       14.0  223.0   385.5   715.0  1361.0              4262.0
RIO GRANDE DO NORTE   5.0   43.0    68.0   114.0   183.0              3999.0
RIO GRANDE DO SUL     3.0  195.0   428.0   615.0   924.0              4249.0
RONDONIA              2.0   63.0    92.0   100.0   238.0              3441.0
RORAIMA               1.0   13.0    24.0    33.0    93.0              3457.0
SANTA CATARINA        5.0  108.0   248.0   382.0  1416.0              4164.0
SAO PAULO            13.0  857.0  1663.0  2373.0  4167.0              4261.0
SERGIPE               1.0   23.0    40.0    53.0    96.0              4202.0
TOCANTINS             1.0   41.0    59.0    68.0   192.0              3453.0

                                ...     ANO          \
                          mean  ...     75%     max
ESTADO                          ...
ACRE                 13.582096  ...  2016.0  2019.0
ALAGOAS               8.347267  ...  2016.0  2019.0
AMAPA                12.677058  ...  2015.0  2019.0
AMAZONAS             10.775515  ...  2016.0  2019.0
BAHIA                 9.406878  ...  2016.0  2019.0
CEARA                 8.530231  ...  2016.0  2019.0
DISTRITO FEDERAL     12.384183  ...  2016.0  2019.0
ESPIRITO SANTO        9.843792  ...  2015.0  2019.0
GOIAS                11.856114  ...  2016.0  2019.0
MARANHAO             12.025352  ...  2016.0  2019.0
MATO GROSSO          13.622934  ...  2015.0  2019.0
MATO GROSSO DO SUL   11.404179  ...  2016.0  2019.0
MINAS GERAIS         10.459741  ...  2015.0  2019.0
PARA                 12.334265  ...  2016.0  2019.0
PARAIBA               9.492584  ...  2016.0  2019.0
PARANA               10.539212  ...  2015.0  2019.0
PERNAMBUCO            9.380088  ...  2016.0  2019.0
PIAUI                11.061338  ...  2016.0  2019.0
RIO DE JANEIRO        9.539249  ...  2016.0  2019.0
RIO GRANDE DO NORTE   8.551917  ...  2015.0  2019.0
RIO GRANDE DO SUL    10.086762  ...  2016.0  2019.0
RONDONIA             12.817467  ...  2016.0  2019.0
RORAIMA              13.234003  ...  2016.0  2019.0
SANTA CATARINA       10.158531  ...  2015.0  2019.0
SAO PAULO             9.488460  ...  2016.0  2019.0
SERGIPE               9.796563  ...  2016.0  2019.0
TOCANTINS            13.156160  ...  2016.0  2019.0

                    PREÇO MÉDIO REVENDA (dolar)                         \
                                          count       mean         std
ESTADO
ACRE                                     3463.0  81.492573  122.300363
ALAGOAS                                  4020.0  50.083604   87.220269
AMAPA                                    2996.0  76.062346  120.854419
AMAZONAS                                 3713.0  64.653091  101.419829
BAHIA                                    4263.0  56.441265   91.658424
CEARA                                    3964.0  51.181386   95.102250
DISTRITO FEDERAL                         3317.0  74.305098  112.827465
ESPIRITO SANTO                           4079.0  59.062750   94.965549
GOIAS                                    3449.0  71.136684  109.652046
MARANHAO                                 3470.0  72.152115  109.498471
MATO GROSSO                              3703.0  81.737606  138.670125
MATO GROSSO DO SUL                       4076.0  68.425072  114.227388
MINAS GERAIS                             4142.0  62.758447  105.133339
PARA                                     3477.0  74.005593  113.029735
PARAIBA                                  4240.0  56.955504   93.697994
PARANA                                   3902.0  63.235275  103.684138
PERNAMBUCO                               4236.0  56.280530   92.175099
PIAUI                                    3394.0  66.368028  103.607285
RIO DE JANEIRO                           4262.0  57.235496   93.753942
RIO GRANDE DO NORTE                      3999.0  51.311500   90.426304
RIO GRANDE DO SUL                        4249.0  60.520574   99.648669
RONDONIA                                 3441.0  76.904802  117.830581
RORAIMA                                  3457.0  79.404017  122.349259
SANTA CATARINA                           4164.0  60.951187  101.079615
SAO PAULO                                4261.0  56.930761   96.605879
SERGIPE                                  4202.0  58.779377   99.587013
TOCANTINS                                3453.0  78.936963  126.114503


                        min      25%     50%      75%      max
ESTADO
ACRE                 10.278  15.3150  19.518  28.3530  486.432
ALAGOAS               6.444  11.8200  16.200  20.7180  415.110
AMAPA                 9.024  13.6425  17.268  25.1520  480.486
AMAZONAS              8.394  13.3620  17.310  22.9920  443.496
BAHIA                 6.474  11.5800  15.672  21.1320  381.462
CEARA                 7.092  11.4780  15.606  20.9460  451.902
DISTRITO FEDERAL      7.296  13.2000  17.904  24.9720  443.574
ESPIRITO SANTO        6.810  12.0900  16.002  21.7230  392.628
GOIAS                 6.972  12.2700  16.872  26.0820  445.920
MARANHAO              7.740  13.1460  16.734  22.6695  455.832
MATO GROSSO           7.224  12.8520  17.082  23.6250  596.142
MATO GROSSO DO SUL    6.582  12.6405  16.254  21.7695  467.466
MINAS GERAIS          6.660  11.5170  15.072  21.6750  475.152
PARA                  8.856  14.1900  17.916  24.5580  463.152
PARAIBA               6.894  11.4195  15.114  21.3015  410.460
PARANA                5.532  11.6460  15.318  21.2010  423.786
PERNAMBUCO            5.994  11.3745  15.528  21.0630  401.958
PIAUI                 8.274  13.4925  16.230  22.3920  438.750
RIO DE JANEIRO        6.216  11.1915  15.390  22.0950  406.074
RIO GRANDE DO NORTE   5.850  11.7000  15.858  21.0360  433.398
RIO GRANDE DO SUL     7.008  12.4380  16.014  22.3740  424.374
RONDONIA              9.198  14.5500  18.366  24.2940  476.112
RORAIMA               7.800  14.9760  18.126  23.8020  512.250
SANTA CATARINA        7.182  12.1320  15.411  20.9175  432.528
SAO PAULO             4.596  11.0220  14.514  20.4420  424.800
SERGIPE               6.930  11.7150  15.450  21.4800  477.780
TOCANTINS             7.356  13.1100  17.592  23.8980  523.620

[27 rows x 120 columns]

In [50]:
data_drop.groupby('ANO').groups

{2004: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...], 2005: [918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, ...], 2006: [2263, 2264, 2265, 2266, 2267, 2268, 2269, 2270, 2271, 2272, 2273, 2274, 2275, 2276, 2277, 2278, 2279, 2280, 2281, 2282, 2283, 2284, 2285, 2286, 2287, 2288, 2289, 2290, 2291, 2292, 2293, 2294, 2295, 2296, 2297, 2298, 2299, 2300, 2301, 2302, 2303, 2304, 2305, 2306, 2307, 2308, 2309, 2310, 2311, 2312, 2313, 2314, 2315, 2316, 2317, 2318, 2319, 2320, 2321, 2322, 2323, 2324, 2325, 2326, 2327, 2328, 2329, 2330, 2331, 2332, 2333, 2334, 2335, 2336, 2337, 2338, 2339, 2340, 2341, 2342, 2343, 2344, 2345, 2346, 2347, 2348, 2349, 2350, 2351, 2352, 2353, 2354, 2355, 2356, 2357, 2358, 2359, 2360, 2361, 2362, ...], 2007: [3694, 3695, 3696, 3697, 3698, 3699, 3700, 3701, 3702, 3703, 3704, 3705, 3706, 3707, 3708, 3709, 3710, 3711, 3712, 3713, 3714, 3715, 3716, 3717, 3718, 3719, 3720, 3721, 3722, 3723, 3724, 3725, 3726, 3727, 3728, 3729, 3730, 3731, 3732, 3733, 3734, 3735, 3736, 3737, 3738, 3739, 3740, 3741, 3742, 3743, 3744, 3745, 3746, 3747, 3748, 3749, 3750, 3751, 3752, 3753, 3754, 3755, 3756, 3757, 3758, 3759, 3760, 3761, 3762, 3763, 3764, 3765, 3766, 3767, 3768, 3769, 3770, 3771, 3772, 3773, 3774, 3775, 3776, 3777, 3778, 3779, 3780, 3781, 3782, 3783, 3784, 3785, 3786, 3787, 3788, 3789, 3790, 3791, 3792, 3793, ...], 2008: [5098, 5099, 5100, 5101, 5102, 5103, 5104, 5105, 5106, 5107, 5108, 5109, 5110, 5111, 5112, 5113, 5114, 5115, 5116, 5117, 5118, 5119, 5120, 5121, 5122, 5123, 5124, 5125, 5126, 5127, 5128, 5129, 5130, 5131, 5132, 5133, 5134, 5135, 5136, 5137, 5138, 5139, 5140, 5141, 5142, 5143, 5144, 5145, 5146, 5147, 5148, 5149, 5150, 5151, 5152, 5153, 5154, 5155, 5156, 5157, 5158, 5159, 5160, 5161, 5162, 5163, 5164, 5165, 5166, 5167, 5168, 5169, 5170, 5171, 5172, 5173, 5174, 5175, 5176, 5177, 5178, 5179, 5180, 5181, 5182, 5183, 5184, 5185, 5186, 5187, 5188, 5189, 5190, 5191, 5192, 5193, 5194, 5195, 5196, 5197, ...], 2009: [6502, 6503, 6504, 6505, 6506, 6507, 6508, 6509, 6510, 6511, 6512, 6513, 6514, 6515, 6516, 6517, 6518, 6519, 6520, 6521, 6522, 6523, 6524, 6525, 6526, 6527, 6528, 6529, 6530, 6531, 6532, 6533, 6534, 6535, 6536, 6537, 6538, 6539, 6540, 6541, 6542, 6543, 6544, 6545, 6546, 6547, 6548, 6549, 6550, 6551, 6552, 6553, 6554, 6555, 6556, 6557, 6558, 6559, 6560, 6561, 6562, 6563, 6564, 6565, 6566, 6567, 6568, 6569, 6570, 6571, 6572, 6573, 6574, 6575, 6576, 6577, 6578, 6579, 6580, 6581, 6582, 6583, 6584, 6585, 6586, 6587, 6588, 6589, 6590, 6591, 6592, 6593, 6594, 6595, 6596, 6597, 6598, 6599, 6600, 6601, ...], 2010: [7853, 7854, 7855, 7856, 7857, 7858, 7859, 7860, 7861, 7862, 7863, 7864, 7865, 7867, 7868, 7870, 7871, 7872, 7873, 7874, 7875, 7876, 7877, 7878, 7880, 7881, 7882, 7883, 7884, 7885, 7886, 7887, 7888, 7889, 7890, 7891, 7892, 7894, 7895, 7896, 7897, 7898, 7899, 7900, 7901, 7902, 7903, 7904, 7905, 7906, 7907, 7908, 7909, 7910, 7911, 7912, 7913, 7914, 7915, 7916, 7917, 7918, 7919, 7920, 7921, 7922, 7923, 7924, 7925, 7926, 7927, 7928, 7929, 7930, 7931, 7932, 7934, 7935, 7936, 7937, 7938, 7939, 7940, 7941, 7942, 7943, 7944, 7945, 7946, 7947, 7948, 7949, 7951, 7952, 7953, 7954, 7955, 7956, 7957, 7958, ...], 2011: [9256, 9257, 9258, 9259, 9260, 9261, 9262, 9263, 9264, 9265, 9266, 9267, 9268, 9269, 9270, 9271, 9272, 9273, 9274, 9275, 9276, 9277, 9278, 9279, 9280, 9281, 9282, 9283, 9284, 9285, 9286, 9287, 9288, 9289, 9290, 9291, 9292, 9293, 9294, 9295, 9296, 9297, 9298, 9299, 9300, 9301, 9302, 9303, 9304, 9305, 9306, 9307, 9308, 9309, 9310, 9311, 9312, 9313, 9314, 9315, 9316, 9317, 9318, 9319, 9320, 9321, 9322, 9323, 9324, 9325, 9326, 9327, 9328, 9329, 9330, 9331, 9332, 9333, 9334, 9335, 9336, 9337, 9338, 9339, 9340, 9341, 9342, 9343, 9344, 9345, 9346, 9347, 9348, 9349, 9350, 9351, 9352, 9353, 9354, 9355, ...], 2012: [10660, 10661, 10662, 10663, 10664, 10665, 10666, 10667, 10668, 10669, 10670, 10671, 10672, 10673, 10674, 10675, 10676, 10677, 10678, 10679, 10680, 10681, 10682, 10683, 10684, 10685, 10686, 10687, 10688, 10689, 10690, 10691, 10692, 10693, 10694, 10695, 10696, 10697, 10698, 10699, 10700, 10701, 10702, 10703, 10704, 10705, 10706, 10707, 10708, 10709, 10710, 10711, 10712, 10713, 10714, 10715, 10716, 10717, 10718, 10719, 10720, 10721, 10722, 10723, 10724, 10725, 10726, 10727, 10729, 10730, 10731, 10732, 10733, 10734, 10735, 10736, 10737, 10738, 10739, 10740, 10741, 10742, 10743, 10744, 10745, 10746, 10747, 10748, 10749, 10750, 10751, 10752, 10753, 10754, 10755, 10756, 10757, 10758, 10759, 10760, ...], 2013: [55759, 55760, 55762, 55763, 55764, 55765, 55766, 55767, 55768, 55769, 55770, 55771, 55772, 55773, 55774, 55775, 55776, 55777, 55778, 55779, 55780, 55781, 55782, 55783, 55784, 55785, 55786, 55787, 55788, 55789, 55790, 55791, 55792, 55793, 55794, 55795, 55796, 55797, 55798, 55799, 55800, 55801, 55802, 55803, 55804, 55805, 55806, 55807, 55808, 55809, 55810, 55811, 55812, 55814, 55815, 55816, 55817, 55820, 55821, 55822, 55823, 55824, 55826, 55827, 55828, 55829, 55830, 55831, 55832, 55833, 55834, 55835, 55837, 55838, 55839, 55840, 55841, 55842, 55843, 55844, 55845, 55846, 55847, 55848, 55849, 55850, 55851, 55852, 55853, 55854, 55855, 55856, 55857, 55858, 55859, 55860, 55861, 55862, 55863, 55864, ...], 2014: [63680, 63681, 63682, 63683, 63684, 63685, 63686, 63687, 63688, 63689, 63690, 63691, 63692, 63693, 63694, 63695, 63696, 63697, 63698, 63699, 63700, 63701, 63702, 63703, 63704, 63705, 63706, 63707, 63708, 63709, 63710, 63711, 63712, 63713, 63714, 63715, 63716, 63717, 63718, 63719, 63720, 63721, 63722, 63723, 63724, 63725, 63726, 63727, 63728, 63729, 63730, 63731, 63732, 63733, 63734, 63735, 63736, 63737, 63738, 63739, 63741, 63742, 63743, 63744, 63745, 63746, 63747, 63748, 63749, 63750, 63751, 63752, 63753, 63754, 63755, 63756, 63757, 63758, 63759, 63760, 63761, 63762, 63763, 63764, 63765, 63766, 63767, 63768, 63769, 63770, 63771, 63772, 63773, 63774, 63775, 63776, 63777, 63778, 63779, 63780, ...], 2015: [71612, 71613, 71614, 71615, 71616, 71617, 71618, 71619, 71620, 71621, 71622, 71623, 71624, 71625, 71626, 71627, 71628, 71629, 71630, 71631, 71632, 71633, 71634, 71635, 71636, 71637, 71638, 71639, 71640, 71641, 71642, 71643, 71644, 71645, 71646, 71647, 71648, 71649, 71650, 71651, 71652, 71653, 71654, 71655, 71656, 71657, 71658, 71659, 71660, 71661, 71662, 71663, 71664, 71665, 71666, 71667, 71668, 71669, 71670, 71671, 71673, 71675, 71676, 71677, 71678, 71679, 71680, 71681, 71682, 71683, 71684, 71685, 71686, 71687, 71688, 71689, 71690, 71691, 71692, 71693, 71694, 71695, 71696, 71697, 71698, 71699, 71700, 71701, 71702, 71703, 71704, 71705, 71706, 71707, 71708, 71709, 71710, 71711, 71712, 71713, ...], 2016: [79383, 79384, 79385, 79386, 79387, 79388, 79389, 79390, 79391, 79392, 79393, 79394, 79395, 79396, 79397, 79398, 79400, 79401, 79402, 79403, 79404, 79405, 79406, 79407, 79408, 79409, 79410, 79411, 79412, 79413, 79414, 79415, 79416, 79417, 79418, 79419, 79420, 79421, 79422, 79423, 79424, 79425, 79426, 79427, 79428, 79429, 79430, 79431, 79432, 79433, 79434, 79435, 79436, 79437, 79438, 79439, 79440, 79441, 79442, 79443, 79444, 79445, 79446, 79447, 79448, 79449, 79450, 79451, 79452, 79453, 79454, 79455, 79456, 79457, 79458, 79459, 79460, 79461, 79462, 79463, 79464, 79465, 79466, 79467, 79468, 79469, 79470, 79471, 79472, 79473, 79474, 79475, 79476, 79477, 79478, 79479, 79480, 79481, 79482, 79483, ...], 2017: [87256, 87257, 87259, 87260, 87261, 87262, 87263, 87264, 87265, 87266, 87267, 87268, 87269, 87270, 87271, 87272, 87273, 87274, 87275, 87276, 87277, 87278, 87279, 87280, 87281, 87282, 87283, 87284, 87285, 87286, 87287, 87288, 87289, 87290, 87291, 87292, 87293, 87294, 87295, 87296, 87297, 87298, 87299, 87300, 87301, 87302, 87303, 87304, 87305, 87306, 87307, 87308, 87309, 87310, 87311, 87312, 87313, 87314, 87315, 87316, 87317, 87318, 87319, 87320, 87321, 87322, 87323, 87324, 87325, 87326, 87327, 87328, 87329, 87330, 87331, 87332, 87333, 87334, 87335, 87336, 87337, 87338, 87339, 87340, 87341, 87342, 87343, 87344, 87345, 87346, 87347, 87348, 87349, 87350, 87351, 87352, 87353, 87354, 87355, 87356, ...], 2018: [95246, 95247, 95249, 95250, 95251, 95252, 95253, 95254, 95255, 95256, 95257, 95258, 95259, 95260, 95261, 95262, 95263, 95264, 95265, 95266, 95267, 95268, 95269, 95270, 95271, 95272, 95273, 95274, 95275, 95276, 95277, 95278, 95279, 95280, 95281, 95282, 95283, 95284, 95285, 95286, 95287, 95288, 95289, 95290, 95291, 95292, 95293, 95294, 95295, 95296, 95297, 95298, 95299, 95300, 95301, 95302, 95303, 95304, 95305, 95306, 95307, 95308, 95309, 95310, 95311, 95312, 95313, 95314, 95315, 95316, 95317, 95318, 95319, 95320, 95321, 95322, 95323, 95324, 95325, 95326, 95327, 95328, 95329, 95330, 95331, 95332, 95333, 95334, 95335, 95336, 95337, 95338, 95339, 95340, 95341, 95342, 95343, 95344, 95345, 95346, ...], 2019: [103069, 103070, 103071, 103072, 103073, 103074, 103075, 103076, 103077, 103078, 103079, 103080, 103081, 103082, 103083, 103084, 103085, 103086, 103087, 103088, 103089, 103090, 103091, 103092, 103093, 103094, 103095, 103096, 103097, 103098, 103099, 103100, 103101, 103102, 103103, 103104, 103105, 103106, 103107, 103108, 103109, 103110, 103111, 103112, 103113, 103114, 103115, 103116, 103117, 103118, 103119, 103120, 103121, 103122, 103123, 103124, 103125, 103126, 103127, 103128, 103129, 103130, 103131, 103132, 103133, 103134, 103135, 103136, 103137, 103138, 103139, 103140, 103141, 103142, 103143, 103144, 103145, 103146, 103147, 103148, 103149, 103150, 103151, 103152, 103153, 103154, 103155, 103156, 103157, 103158, 103159, 103160, 103161, 103162, 103163, 103164, 103165, 103166, 103167, 103168, ...]}

In [51]:
data_drop.groupby('ESTADO').get_group('SAO PAULO').describe()

,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,PREÇO MÉDIO REVENDA (dolar)
count,4261.000000,4261.00000,4261.000000,4261.000000,4261.000000,4261.000000,4261.000000,4261.000000,4261.000000,4261.000000,4261.000000,4261.000000,4261.000000,4261.000000,4261.000000
mean,1594.034264,9.48846,0.712168,7.343741,12.025374,2.337622,0.060542,7.150838,0.684919,5.374443,9.829807,0.071757,6.486271,2011.772823,56.930761
std,1015.331098,16.10098,1.433630,11.894187,20.874773,4.708991,0.025825,11.518492,1.324546,8.331703,16.936783,0.056365,3.443182,4.398679,96.605879
min,13.000000,0.76600,0.050000,0.590000,1.099000,0.135000,0.024000,0.570000,0.000000,0.339800,0.822000,0.000000,1.000000,2004.000000,4.596000
25%,857.000000,1.83700,0.094000,1.557000,2.299000,0.273000,0.039000,1.547000,0.063000,1.259700,1.819000,0.028000,4.000000,2008.000000,11.022000
50%,1663.000000,2.41900,0.119000,2.130000,2.899000,0.342000,0.055000,2.107000,0.093000,1.907200,2.377000,0.048000,6.000000,2012.000000,14.514000
75%,2373.000000,3.40700,0.180000,2.998000,3.999000,0.441000,0.080000,2.990000,0.189000,2.590000,3.331000,0.109000,9.000000,2016.000000,20.442000
max,4167.000000,70.80000,7.171000,55.000000,99.000000,22.989000,0.201000,51.038000,6.240000,42.000000,75.000000,0.415000,12.000000,2019.000000,424.800000

In [52]:
data_drop.groupby(['PRODUTO', 'REGIÃO']).describe()

                              NÚMERO DE POSTOS PESQUISADOS               \
                                                     count         mean
PRODUTO          REGIÃO
ETANOL HIDRATADO CENTRO OESTE                       3122.0   155.514414
                 NORDESTE                           7046.0   154.143770
                 NORTE                              5177.0    47.731312
                 SUDESTE                            3137.0  1038.720115
                 SUL                                2353.0   454.889928
GASOLINA COMUM   CENTRO OESTE                       3134.0   155.447352
                 NORDESTE                           7063.0   174.051678
                 NORTE                              5464.0    77.837665
                 SUDESTE                            3140.0  1051.909236
                 SUL                                2354.0   495.972387
GLP              CENTRO OESTE                       3098.0   202.113944
                 NORDESTE                           6410.0   127.294072
                 NORTE                              5327.0    91.767224
                 SUDESTE                            3137.0   757.155881
                 SUL                                2343.0   487.431498
GNV              CENTRO OESTE                        847.0     3.759150
                 NORDESTE                           5176.0    17.498068
                 NORTE                               243.0     1.378601
                 SUDESTE                            2841.0    81.839493
                 SUL                                1899.0    21.242759
ÓLEO DIESEL      CENTRO OESTE                       3134.0   131.940332
                 NORDESTE                           7061.0   135.536185
                 NORTE                              5465.0    68.135956
                 SUDESTE                            3140.0   771.300955
                 SUL                                2354.0   364.170348
ÓLEO DIESEL S10  CENTRO OESTE                       1210.0    76.054545
                 NORDESTE                           3032.0    93.857190
                 NORTE                              2324.0    40.495267
                 SUDESTE                            1349.0   419.743514
                 SUL                                1012.0   230.283597

                                                                         \
                                      std   min     25%    50%      75%
PRODUTO          REGIÃO
ETANOL HIDRATADO CENTRO OESTE   79.854557   4.0   88.00  140.0   206.75
                 NORDESTE      120.286118   1.0   61.00  109.0   202.00
                 NORTE          31.786616   1.0   18.00   40.0    74.00
                 SUDESTE       930.107749   6.0  295.00  729.0  1323.00
                 SUL           179.365613  11.0  361.00  501.0   566.00
GASOLINA COMUM   CENTRO OESTE   80.157376   6.0   88.00  139.0   205.75
                 NORDESTE      124.697374   3.0   95.00  124.0   227.00
                 NORTE          54.775646   4.0   36.75   59.0   110.25
                 SUDESTE       927.410130  16.0  299.00  740.0  1369.25
                 SUL           176.038512  15.0  377.00  519.0   612.00
GLP              CENTRO OESTE  147.885877   2.0  107.00  133.0   224.75
                 NORDESTE       98.377845   2.0   49.00   90.0   200.00
                 NORTE          65.669797   3.0   31.00   84.0   124.00
                 SUDESTE       652.378178   4.0  223.00  411.0  1096.00
                 SUL           229.566227  12.0  298.00  527.0   703.00
GNV              CENTRO OESTE    2.007924   1.0    2.00    3.0     5.00
                 NORDESTE        9.433991   1.0   10.00   16.0    24.00
                 NORTE           0.633659   1.0    1.00    1.0     2.00
                 SUDESTE        73.698316   1.0   15.00   55.0   127.00
                 SUL            10.805715   1.0   13.00   20.0    29.00
ÓLEO DIESEL      CENTRO OESTE   77.849589   6.0   78.00  116.0   174.00
                 NORDESTE      107.442412   2.0   56.00  103.0   156.00
                 NORTE          46.695648   4.0   33.00   52.0    98.00
                 SUDESTE       684.255256  12.0  208.00  587.0   910.00
                 SUL           153.844415  23.0  240.00  360.0   470.00
ÓLEO DIESEL S10  CENTRO OESTE   38.150505   5.0   45.25   73.0   100.00
                 NORDESTE       71.693189   2.0   41.00   58.0   143.25
                 NORTE          31.537397   1.0   16.00   34.0    52.00
                 SUDESTE       383.141155   9.0  100.00  307.0   467.00
                 SUL            69.705482   7.0  183.75  244.0   285.00

                                      PREÇO MÉDIO REVENDA             ...  \
                                  max               count       mean  ...
PRODUTO          REGIÃO                                               ...
ETANOL HIDRATADO CENTRO OESTE   487.0              3122.0   2.135670  ...
                 NORDESTE       543.0              7046.0   2.320266  ...
                 NORTE          150.0              5177.0   2.511624  ...
                 SUDESTE       4111.0              3137.0   2.163621  ...
                 SUL            871.0              2353.0   2.268156  ...
GASOLINA COMUM   CENTRO OESTE   492.0              3134.0   3.077476  ...
                 NORDESTE       625.0              7063.0   3.001887  ...
                 NORTE          265.0              5464.0   3.149501  ...
                 SUDESTE       4167.0              3140.0   3.000565  ...
                 SUL            924.0              2354.0   2.972569  ...
GLP              CENTRO OESTE   766.0              3098.0  48.176747  ...
                 NORDESTE       493.0              6410.0  41.966090  ...
                 NORTE          383.0              5327.0  47.065572  ...
                 SUDESTE       2165.0              3137.0  42.081544  ...
                 SUL           1416.0              2343.0  43.490318  ...
GNV              CENTRO OESTE    10.0               847.0   1.856312  ...
                 NORDESTE        51.0              5176.0   1.881722  ...
                 NORTE            5.0               243.0   2.084399  ...
                 SUDESTE        294.0              2841.0   1.716074  ...
                 SUL             60.0              1899.0   1.865612  ...
ÓLEO DIESEL      CENTRO OESTE   430.0              3134.0   2.481286  ...
                 NORDESTE       535.0              7061.0   2.346950  ...
                 NORTE          240.0              5465.0   2.571048  ...
                 SUDESTE       3237.0              3140.0   2.339699  ...
                 SUL            712.0              2354.0   2.332293  ...
ÓLEO DIESEL S10  CENTRO OESTE   185.0              1210.0   3.294752  ...
                 NORDESTE       277.0              3032.0   3.041966  ...
                 NORTE          146.0              2324.0   3.316231  ...
                 SUDESTE       1374.0              1349.0   3.056194  ...
                 SUL            368.0              1012.0   2.981775  ...

                                  ANO         PREÇO MÉDIO REVENDA (dolar)  \
                                  75%     max                       count
PRODUTO          REGIÃO
ETANOL HIDRATADO CENTRO OESTE  2015.0  2019.0                      3122.0
                 NORDESTE      2015.0  2019.0                      7046.0
                 NORTE         2015.0  2019.0                      5177.0
                 SUDESTE       2015.0  2019.0                      3137.0
                 SUL           2015.0  2019.0                      2353.0
GASOLINA COMUM   CENTRO OESTE  2015.0  2019.0                      3134.0
                 NORDESTE      2015.0  2019.0                      7063.0
                 NORTE         2015.0  2019.0                      5464.0
                 SUDESTE       2015.0  2019.0                      3140.0
                 SUL           2015.0  2019.0                      2354.0
GLP              CENTRO OESTE  2015.0  2019.0                      3098.0
                 NORDESTE      2015.0  2019.0                      6410.0
                 NORTE         2015.0  2019.0                      5327.0
                 SUDESTE       2015.0  2019.0                      3137.0
                 SUL           2015.0  2019.0                      2343.0
GNV              CENTRO OESTE  2014.0  2019.0                       847.0
                 NORDESTE      2015.0  2019.0                      5176.0
                 NORTE         2016.0  2019.0                       243.0
                 SUDESTE       2015.0  2019.0                      2841.0
                 SUL           2015.0  2019.0                      1899.0
ÓLEO DIESEL      CENTRO OESTE  2015.0  2019.0                      3134.0
                 NORDESTE      2015.0  2019.0                      7061.0
                 NORTE         2015.0  2019.0                      5465.0
                 SUDESTE       2015.0  2019.0                      3140.0
                 SUL           2015.0  2019.0                      2354.0
ÓLEO DIESEL S10  CENTRO OESTE  2018.0  2019.0                      1210.0
                 NORDESTE      2017.0  2019.0                      3032.0
                 NORTE         2017.0  2019.0                      2324.0
                 SUDESTE       2017.0  2019.0                      1349.0
                 SUL           2017.0  2019.0                      1012.0

                                                                         \
                                     mean        std      min       25%
PRODUTO          REGIÃO
ETANOL HIDRATADO CENTRO OESTE   12.814019   3.368789    6.972   10.2840
                 NORDESTE       13.921593   3.626245    7.086   10.9500
                 NORTE          15.069745   3.880684    7.356   12.1980
                 SUDESTE        12.981724   3.908916    4.596   10.1520
                 SUL            13.608933   4.217264    5.532   10.3260
GASOLINA COMUM   CENTRO OESTE   18.464858   3.691740   11.616   16.0035
                 NORDESTE       18.011325   3.844175   11.694   15.5040
                 NORTE          18.897009   3.847496   11.970   16.2285
                 SUDESTE        18.003392   4.191439   11.328   15.0120
                 SUL            17.835413   3.741344   11.766   15.2580
GLP              CENTRO OESTE  289.060480  91.224268  172.746  223.9980
                 NORDESTE      251.796538  72.382459  170.202  199.3725
                 NORTE         282.393433  87.322490  168.516  217.9770
                 SUDESTE       252.489267  69.148430  168.156  201.8160
                 SUL           260.941908  69.844529  176.640  208.7550
GNV              CENTRO OESTE   11.137870   2.543169    6.582    9.4140
                 NORDESTE       11.290334   3.137977    5.850    9.5760
                 NORTE          12.506395   3.733377    8.394    8.3940
                 SUDESTE        10.296444   2.772587    5.976    8.5440
                 SUL            11.193675   2.944220    7.008    8.9940
ÓLEO DIESEL      CENTRO OESTE   14.887717   3.761582    8.610   12.1980
                 NORDESTE       14.081699   3.634231    7.878   11.4000
                 NORTE          15.426290   3.905961    8.700   12.5160
                 SUDESTE        14.038192   3.531849    8.136   11.2560
                 SUL            13.993759   3.167072    8.244   11.7060
ÓLEO DIESEL S10  CENTRO OESTE   19.768512   2.527407   13.830   17.5455
                 NORDESTE       18.251796   2.649300   12.780   15.6000
                 NORTE          19.897384   3.174261   13.158   17.2980
                 SUDESTE        18.337165   2.510376   13.080   15.9000
                 SUL            17.890648   2.192823   12.906   15.9780


                                   50%       75%      max
PRODUTO          REGIÃO
ETANOL HIDRATADO CENTRO OESTE   12.003   14.8740   21.588
                 NORDESTE       13.116   16.0200   23.562
                 NORTE          14.034   17.3760   24.612
                 SUDESTE        12.258   15.4020   24.690
                 SUL            12.678   15.6060   25.722
GASOLINA COMUM   CENTRO OESTE   17.139   20.7585   29.778
                 NORDESTE       16.446   20.5470   29.706
                 NORTE          17.598   21.5085   32.172
                 SUDESTE        16.758   20.7090   30.714
                 SUL            16.389   20.0535   29.718
GLP              CENTRO OESTE  257.031  335.4255  596.142
                 NORDESTE      221.130  290.1060  477.780
                 NORTE         253.866  324.4500  523.620
                 SUDESTE       229.680  295.5540  475.152
                 SUL           239.856  292.4010  432.528
GNV              CENTRO OESTE   10.494   13.0080   19.434
                 NORDESTE       10.803   12.0675   22.866
                 NORTE          12.360   15.9000   19.440
                 SUDESTE         9.978   11.4240   20.394
                 SUL            10.212   12.9570   20.856
ÓLEO DIESEL      CENTRO OESTE   13.479   18.1140   24.972
                 NORDESTE       12.492   17.2020   24.060
                 NORTE          14.034   18.4920   28.644
                 SUDESTE        12.495   16.9500   23.964
                 SUL            12.540   16.7070   22.800
ÓLEO DIESEL S10  CENTRO OESTE   20.124   21.7140   25.200
                 NORDESTE       18.519   20.0280   24.162
                 NORTE          19.893   21.9180   29.268
                 SUDESTE        18.546   20.3160   24.480
                 SUL            17.946   19.5120   22.890

[30 rows x 120 columns]